// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(DB_PauloVictorContext))]
    partial class DB_PauloVictorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.models.Ativo", b =>
                {
                    b.Property<int>("IdAtivo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("LoteMinimo")
                        .HasColumnName("lote_minimo");

                    b.HasKey("IdAtivo");

                    b.ToTable("Ativo");
                });

            modelBuilder.Entity("WebApi.models.Ordem", b =>
                {
                    b.Property<int>("IdOrdem")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_ordem")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClasseNegociacao")
                        .IsRequired()
                        .HasColumnName("classe_negociacao")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Data")
                        .HasColumnName("data")
                        .HasColumnType("date");

                    b.Property<int>("FkIdAtivo")
                        .HasColumnName("fk_id_ativo");

                    b.Property<double>("Preco")
                        .HasColumnName("preco");

                    b.Property<double>("Quantidade")
                        .HasColumnName("quantidade");

                    b.HasKey("IdOrdem");

                    b.ToTable("Ordem");
                });
#pragma warning restore 612, 618
        }
    }
}
